version: "3"

services:
  testpg:
    image: postgres
    restart: always
    volumes:
      - ./db-sql/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
    ports:
      - "5432:5432"

  testadm:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
